#!/bin/bash

# /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf should exist
# /path/to/nowplaying.txt or some nowplaying.txt should exist and referenced at line 14
# YOUTUBE_URL can be modified to STREAM_URL to use with others platforms

STORAGE=/mnt/free-tekno.com/storage

VBR="3000k" # 1280x720 resolution, raise to match full HD/4K
FPS="30"
QUAL="ultrafast"
YOUTUBE_URL="rtmp://a.rtmp.youtube.com/live2"
YOUTUBE_KEY="$(cat .stream_key_youtube)"
VIDEO_SOURCE="$STORAGE/video.mp4"
AUDIO_SOURCE="https://your.webradio/path.mp3"
NP_SOURCE="$STORAGE/nowplaying.txt" # nowplaying.txt generated by nowplaying.php
FONT_SIZE="25"
THREAD_QUEUE_SIZE="512" # should be increased if errors
AUDIO_THREADS="2" # should be <= cpu/cores
AUDIO_SAMPLE_RATE="44100"
MP3_BITRATE="320000"
AUDIO_BUFFER="2048k"

while :
do

ffmpeg \
    -re -f lavfi -i "movie=filename=$VIDEO_SOURCE:loop=0, setpts=N/(FRAME_RATE*TB)" \
    -thread_queue_size $THREAD_QUEUE_SIZE -i "$AUDIO_SOURCE" \
    -map 0:v:0 -map 1:a:0 \
    -map_metadata:g 1:g \
    -vf drawtext="fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: fontsize=$FONT_SIZE: \
     box=0: boxcolor=black@0.5: boxborderw=20: \
     textfile=$NP_SOURCE: reload=1: fontcolor=white@0.8: x=50: y=th" \
    -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec libmp3lame -ar $AUDIO_SAMPLE_RATE -threads $AUDIO_THREADS -qscale:v 3 -b:a $MP3_BITRATE -bufsize $AUDIO_BUFFER \
    -f flv "$YOUTUBE_URL/$YOUTUBE_KEY"

done
